import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import { Heart, ImagePlus, Music2, Pause, Play, RotateCcw, Sparkles, Upload } from 'lucide-react';

const noMessages = ['No... not letting you go 🥺', 'Yenaku venum us 🥺', 'Nenga... nanum... plsss 🥺', 'Vera yarum vena 🥺', 'Yen chelam yaruuuu? 🥺', "You know the answer... it's you. ❤️", 'No escape for you, okay? 🙈', 'Now come back and click YES. 🥺❤️'];
type Photo = string | null;

function useLocalPhoto(id: string) {
  const [photo, setPhoto] = useState<Photo>(() => localStorage.getItem(`jothi-photo-${id}`));
  const onUpload = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const result = reader.result as string; setPhoto(result); localStorage.setItem(`jothi-photo-${id}`, result); }; reader.readAsDataURL(file); };
  return { photo, onUpload };
}

function PhotoCard({ id, caption, subtext }: { id: string; caption: string; subtext: string }) {
  const { photo, onUpload } = useLocalPhoto(id);
  return <label className="photo-card"><div className="photo-frame">{photo ? <img src={photo} alt={caption} /> : <><ImagePlus size={30} /><span>your memory belongs here</span></>}</div><span className="photo-caption">{caption}</span><small>{subtext}</small><span className="upload-label"><Upload size={13} /> Change Photo</span><input type="file" accept="image/*" onChange={onUpload} /></label>;
}
function VideoMemory() {
  const [video, setVideo] = useState<string | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const onUpload = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (video) URL.revokeObjectURL(video);
    setVideo(URL.createObjectURL(file));
  };
  const keepToFiveSeconds = () => {
    const player = videoRef.current;
    if (player && player.currentTime >= 5) {
      player.currentTime = 0;
      player.play().catch(() => {});
    }
  };
  return <label className="video-memory glass-card">
    <div className="video-frame">{video ? <video ref={videoRef} src={video} autoPlay muted loop playsInline onTimeUpdate={keepToFiveSeconds} /> : <><span className="video-play">▶</span><span>add our little 5 second memory</span></>}</div>
    <span className="video-caption">oruu kissyyyy ❤️</span>
    <small>A LITTLE 5 SECOND MEMORY</small>
    <span className="upload-label"><Upload size={13} /> Add 5 Sec Video</span>
    <input type="file" accept="video/*" onChange={onUpload} />
  </label>;
}

function BackgroundHearts() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext('2d'); if (!context) return; let animationFrame = 0; const hearts = Array.from({ length: 28 }, () => ({ x: Math.random(), y: Math.random(), size: 7 + Math.random() * 14, speed: .00012 + Math.random() * .00022, drift: Math.random() * 2 - 1, alpha: .12 + Math.random() * .3 })); const draw = () => { const ratio = window.devicePixelRatio || 1; canvas.width = window.innerWidth * ratio; canvas.height = window.innerHeight * ratio; canvas.style.width = `${window.innerWidth}px`; canvas.style.height = `${window.innerHeight}px`; context.setTransform(ratio, 0, 0, ratio, 0, 0); context.clearRect(0, 0, window.innerWidth, window.innerHeight); hearts.forEach((heart) => { heart.y -= heart.speed; heart.x += Math.sin(Date.now() * .0004 + heart.drift) * .00008; if (heart.y < -.08) { heart.y = 1.05; heart.x = Math.random(); } const x = heart.x * window.innerWidth; const y = heart.y * window.innerHeight; const s = heart.size; context.save(); context.translate(x, y); context.rotate(-.18); context.fillStyle = `rgba(255, 77, 119, ${heart.alpha})`; context.beginPath(); context.moveTo(0, s * .8); context.bezierCurveTo(-s * 1.2, -s * .05, -s * .55, -s * .8, 0, -s * .25); context.bezierCurveTo(s * .55, -s * .8, s * 1.2, -s * .05, 0, s * .8); context.fill(); context.restore(); }); animationFrame = requestAnimationFrame(draw); }; draw(); return () => cancelAnimationFrame(animationFrame); }, []);
  return <canvas className="heart-canvas" ref={canvasRef} aria-hidden="true" />;
}

function MusicBanner() {
  const [playing, setPlaying] = useState(false); const [song, setSong] = useState<string | null>(null); const [songName, setSongName] = useState(''); const [audioError, setAudioError] = useState(false); const audioRef = useRef<HTMLAudioElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const onSong = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const isAudio = file.type.startsWith('audio/') || /\.(mp3|wav|m4a|ogg|aac|flac|webm)$/i.test(file.name); if (!isAudio) { setAudioError(true); return; } const url = URL.createObjectURL(file); setSong((current) => { if (current) URL.revokeObjectURL(current); return url; }); setSongName(file.name); setAudioError(false); event.target.value = ''; };
  useEffect(() => { if (!song || !audioRef.current) return; const player = audioRef.current; player.load(); player.play().then(() => { setPlaying(true); setAudioError(false); }).catch(() => { setPlaying(false); setAudioError(true); }); }, [song]);
  useEffect(() => { const openUploader = () => fileInputRef.current?.click(); window.addEventListener('open-song-uploader', openUploader); return () => window.removeEventListener('open-song-uploader', openUploader); }, []);
  const toggle = () => { if (!audioRef.current || !song) { fileInputRef.current?.click(); return; } if (playing) { audioRef.current.pause(); setPlaying(false); } else audioRef.current.play().then(() => setPlaying(true)).catch(() => setPlaying(false)); };
  return <div className="music-banner"><button className="music-toggle" onClick={toggle} title={song ? (playing ? 'Pause music' : 'Play music') : 'Choose a song first'}>{playing ? <Pause size={15} /> : <Play size={15} fill="currentColor" />}</button><div className="music-copy"><span className="playing-status"><i className={playing ? 'pulse-dot' : ''} /> {playing ? 'PLAYING' : song ? 'READY' : 'ADD A SONG'}</span><strong>{audioError ? 'File could not be played' : song ? songName : 'Choose an audio file to begin'}</strong></div><div className={`equalizer ${playing ? 'is-playing' : ''}`}><i /><i /><i /><i /><i /></div><button type="button" className="song-upload" title="Add or change song" onClick={() => fileInputRef.current?.click()}><Music2 size={16} /><span>🎵 Choose Audio File</span><input ref={fileInputRef} type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.aac,.flac,.webm" onChange={onSong} /></button><audio ref={audioRef} src={song ?? undefined} onError={() => setAudioError(true)} onEnded={() => setPlaying(false)} /></div>;
}

function Progress({ slide, onJump }: { slide: number; onJump: (value: number) => void }) { return <div className="progress-dots" aria-label="Story progress">{[0, 1, 2, 3, 4].map((item) => <button key={item} className={item === slide ? 'active' : item < slide ? 'visited' : ''} onClick={() => item <= slide && onJump(item)} aria-label={`Go to chapter ${item + 1}`} />)}</div>; }
function Nav({ slide, setSlide }: { slide: number; setSlide: (value: number) => void }) { return <header className="topbar"><div className="brand"><Heart size={17} fill="currentColor" /> <span>Jothi <em>and</em> Vibi</span></div><Progress slide={slide} onJump={setSlide} /><MusicBanner /></header>; }
function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick: () => void; secondary?: boolean }) { return <button className={secondary ? 'button secondary' : 'button'} onClick={onClick}>{children}</button>; }

function App() {
  const [slide, setSlide] = useState(0); const [noCount, setNoCount] = useState(0); const [noPosition, setNoPosition] = useState({ x: 0, y: 0 }); const [celebrating, setCelebrating] = useState(false); const [sealed, setSealed] = useState(false);
  const moveNo = () => { setNoCount((count) => Math.min(count + 1, noMessages.length)); setNoPosition({ x: (Math.random() - .5) * 260, y: (Math.random() - .5) * 150 }); };
  const chooseYes = () => { setCelebrating(true); window.setTimeout(() => { setCelebrating(false); setSlide(4); }, 2200); };
  const reset = () => { setSlide(0); setNoCount(0); setNoPosition({ x: 0, y: 0 }); setSealed(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className="app-shell"><BackgroundHearts /><Nav slide={slide} setSlide={setSlide} /><main className="story-main">
    {slide === 0 && <section className="slide opening-slide"><div className="heart-emblem"><Heart fill="currentColor" /></div><p className="eyebrow">A letter for the one who feels like home</p><h1>Hii babyyy <span>❤️</span></h1><p className="script subtitle">Manichukonga d yen thangoo 🥺</p><div className="glass-card intro-card"><p>Okay... enough of everything.<br />Let's forget all the little things for a moment...<br />and start from the very beginning. ❤️</p><div className="divider" /><p>Our story... our memories... our little world. 🫶🏻</p><strong>Ready, babby? 👀❤️</strong></div><Button onClick={() => setSlide(1)}>Continue <span>➔</span></Button><p className="signature">Made with ❤️ specially for Jothi Ramalingar 🌸</p></section>}
    {slide === 1 && <section className="slide chapter-slide"><p className="badge">✨ CHAPTER 1: THE SPARK</p><h2>And then... there was <em>28th March.</em> ✨</h2><div className="glass-card story-copy"><p>It all started from Bumble... But honestly, we didn't even talk that much in the beginning. 😂 Just a few conversations here and there...</p><p>And then somehow, we started talking more. A little more every day. A little closer every time. ❤️</p><blockquote>“I was literally falling for you from Day 1. 🥹”</blockquote><p>I don't even know why. There was no proper reason. No big moment. I just... started falling for you.</p><p className="accent-line">Maybe my heart knew something that my brain didn't. 🤍</p><p>And without even realizing it... you were slowly becoming someone really special to me. 🙈</p></div><div className="section-break"><span>AND THEN CAME...</span><h3>14th April. ❤️</h3><p>The day we finally met.</p><em>“But little did I know... that meeting you would make me fall even harder. 🫶🏻”</em></div><PhotoCard id="meeting" caption="14th April – The Day We Met" subtext="WHEN MY WHOLE WORLD CHANGED ❤️" /><div className="controls"><Button secondary onClick={() => setSlide(0)}>← Back</Button><Button onClick={() => setSlide(2)}>Continue ➔</Button></div></section>}
    {slide === 2 && <section className="slide chapter-slide"><p className="badge">✨ CHAPTER 2: THE FIRST DATE</p><h2>The Day I Knew... <em>Our First Date ❤️</em></h2><p className="script lead">The moment time stood completely still</p><PhotoCard id="date" caption="Our First Date" subtext="THE BEGINNING OF FOREVER ✨" /><div className="glass-card date-copy"><blockquote>“There is always one night or one day when you realise you met someone... The meet when you see his soul, feel him around you even without seeing... There's always that one night that tells you that you're falling... ✨”</blockquote><h4>❤️ HOW THAT DAY FELT</h4><p>The moment we sat together, every hesitation vanished into the night. It wasn't just a simple date — it was the quiet certainty of two souls feeling completely at peace. Looking into your eyes, laughing at the smallest things, I knew right then that you were never going to be just another person to me.</p><p>Laying on your chest that's always felt like home, I could smell the scent of your perfume at the back of your neck but...</p><div className="special-quote">When the scent of the perfume fades away and your hands lay on my skin, you will always be my home 🫶🏻 ❤️</div></div><PhotoCard id="home" caption="You Will Always Be My Home 🫶🏻 ❤️" subtext="OUR FIRST DATE MEMORY" /><div className="controls"><Button secondary onClick={() => setSlide(1)}>← Previous Chapter</Button><Button onClick={() => setSlide(3)}>Continue ➔</Button></div></section>}
    {slide === 3 && <section className="slide question-slide"><p className="badge">A LITTLE QUESTION FOR YOU</p><div className="question-card glass-card"><div className="heart-emblem small"><Heart fill="currentColor" /></div><h2>Will you promise to be mine forever, babby? 🥺❤️</h2><p className="lead">Think very carefully before you choose... 🙈👉👈</p><p className="hint">(There is only one true answer in your heart ❤️)</p><div className="dialogue">{noCount > 0 ? noMessages[noCount - 1] : 'I am waiting for your heart to answer...'}</div><div className="choice-area"><button className="button yes-button" onClick={chooseYes}>YES ❤️ ✨</button><button className="no-button" style={{ transform: `translate(${noPosition.x}px, ${noPosition.y}px)` }} onMouseEnter={moveNo} onTouchStart={moveNo} onClick={(event) => { event.preventDefault(); moveNo(); }}>NO 🥺</button></div><p className="hint footer-hint">Hehe, you can't click NO anymore, babby... the button is running away! 🏃‍♀️💨</p></div></section>}
    {slide === 4 && <section className="slide letter-slide"><p className="badge">❤️ MY APOLOGY & FOREVER PROMISE</p><p className="script lead">Manichukonga d yen thangoo 🥺</p><h2>To My Dearest <em>Jothi Ramalingar ❤️</em></h2><p className="lead">A promise straight from my soul to yours</p><div className="promise-card glass-card"><Sparkles size={21} /><h3>{sealed ? '✅ My Sacred Promise Is Sealed ❤️' : 'My Solemn Promise To You'}</h3><p>“I promise with every beat of my heart that I will never hurt you anymore. You are too precious to ever see you sad because of me.”</p>{sealed ? <div className="sealed">Forever protecting your smile and your heart, my babby. 🫶🏻</div> : <Button onClick={() => setSealed(true)}>👉 Tap to Seal My Promise 🩸❤️</Button>}</div><article className="letter-card glass-card"><div className="letter-heading"><span className="script">From Your Thangoo ❤️</span><Heart size={17} fill="currentColor" /></div><p>Manichukonga d yen thangoo 🥺...</p><p>It breaks my heart knowing that I caused you pain. There is honestly nothing in this world more important to me than your smile, your peace, and us. I never ever want to be the reason tears come to your eyes or worry fills your thoughts.</p><p>Looking back at where everything started — from that very first hello on Bumble, to our late-night conversations that slowly became the safest part of my everyday life. 28th March brought you into my life, and 14th April showed me that my heart had already surrendered to you.</p><blockquote>“Laying on your chest that's always felt like home... when the scent of perfume fades away and your hands lay on my skin, you will always be my home 🫶🏻 💕”</blockquote><p>I promise to listen to you more, cherish you more, hold you tighter, and love you better every single day. I won't ever hurt you anymore. Vera yarum vena... yenaku nenga mattum pothum.</p><p>Please let go of the hurt, hold my hand, and let's restart our little world together. ❤️</p><p>With endless love, deepest apology, and all my heart,<br /><span className="script closing">Forever your thangoo 🫶🏻</span></p></article><div className="gallery-heading"><h3>Our Little World ✨</h3><p>The moments that remind me why I love you so much</p></div><div className="gallery"><PhotoCard id="memory-one" caption="Us ❤️" subtext="THROUGH EVERYTHING" /><PhotoCard id="memory-two" caption="Forever My Home 🫶🏻 ❤️" subtext="YOU & ME" /></div><VideoMemory /><div className="controls bottom-controls"><Button secondary onClick={reset}><RotateCcw size={16} /> Read Our Story Again From The Beginning</Button><button className="button secondary song-bottom" onClick={() => window.dispatchEvent(new Event('open-song-uploader'))}><Music2 size={16} /> 🎵 Add / Change Song</button></div><p className="signature">Made with endless love and a sincere heart for Jothi Ramalingar 🌸</p></section>}
  </main>{celebrating && <div className="celebration"><div className="confetti">{Array.from({ length: 32 }, (_, index) => <span key={index} style={{ '--i': index } as React.CSSProperties}>♥</span>)}</div><div className="celebration-modal"><div>💖</div><h3>I Knew It! Forever & Always! ❤️</h3><p>Opening my promise & love letter to you... ✨</p></div></div>}</div>;
}

export default App;
